spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sb_users
    username: sb
    password: 'sb123123'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
